spring:
  #1. ?????
  datasource:
    url: jdbc:mysql://localhost:3306/iot?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 2. Redis ?? (?????)
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0 # ????0??
      timeout: 10000ms
  # 3. Sa-Token ??
sa-token:
  token-name: Authorization # ???????? Token ??????
  timeout: 2592000 # token ??????????? 30 ?
  is-concurrent: true # ????????????
  is-share: true # ????????????????? token
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

